# Servidor
server.port=${PORT:8080}

# Conexión a Supabase (usando DIRECT_URL)
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.kzkurdrjugcnnnughcis
spring.datasource.password=HelpDesk2026!

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true