-- Table: public.tickets

-- DROP TABLE IF EXISTS public.tickets;

CREATE TABLE IF NOT EXISTS public.tickets
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    categoria character varying(255) COLLATE pg_catalog."default" NOT NULL,
    descripcion character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(255) COLLATE pg_catalog."default" NOT NULL,
    fecha_creacion timestamp(6) without time zone,
    prioridad character varying(255) COLLATE pg_catalog."default" NOT NULL,
    titulo character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT tickets_pkey PRIMARY KEY (id),
    CONSTRAINT tickets_categoria_check CHECK (categoria::text = ANY (ARRAY['HARDWARE'::character varying, 'SOFTWARE'::character varying, 'REDES'::character varying, 'ACCESOS'::character varying, 'OTROS'::character varying]::text[])),
    CONSTRAINT tickets_estado_check CHECK (estado::text = ANY (ARRAY['ABIERTO'::character varying, 'EN_PROCESO'::character varying, 'RESUELTO'::character varying, 'CERRADO'::character varying]::text[])),
    CONSTRAINT tickets_prioridad_check CHECK (prioridad::text = ANY (ARRAY['BAJA'::character varying, 'MEDIA'::character varying, 'ALTA'::character varying, 'URGENTE'::character varying]::text[]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tickets
    OWNER to postgres;