spring.application.name=helpdesk
server.port=8080

# Configuración para la base de datos PostgreSQL en Render
spring.datasource.url=jdbc:postgresql://dpg-d9l5e9ht0dsc73fqursg-a.oregon-postgres.render.com:5432/helpdesk_lq4q?sslmode=require
spring.datasource.username=admin
spring.datasource.password=pExROBzwcHmijps2qGMOcFZIeTreC3aE
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
